### ISSUE TITLE
Auto Tags Issue

### ISSUE THREAD

**Issue by hankcs** [DoodleJZ/HPSG-Neural-Parser#10]
Hi, I'm a little bit confused if `02-21.10way.clean` is auto tagged, how did you measure the constituency parsing score? I checked the 3th and 4th columns are the same. If they are auto tagged then you don't have gold truth for constituency parsing, otherwise the dependency parsing score is biased.

**Comment by DoodleJZ** [comment]
Which Tag do you mean?  The POS tag or the label of constituency parsing?

**Comment by DoodleJZ** [comment]
I use the POS tags in 02-21.10way.clean which are not golden tag.

**Comment by hankcs** [comment]
I mean the POS tags. Yes, you mentioned the POS accuracy is 97.3%, so I assume the data contains no gold tag. Then could you explain how did you measure the acc for constituency parsing without knowing gold POS tags? In my understanding, the labels of constituency parsing are the superset of POS tags, as the labels to terminals are just the POS tags for them.

**Comment by DoodleJZ** [comment]
The acc of constituency parsing only measure the labels of constituency parsing without POS tags,  otherwise only the label of internal node in the constituency tree.

**Comment by hankcs** [comment]
I see. Thank you for your clarification.
