### ISSUE TITLE
No such file or directory: 'data/glove.gz'

### ISSUE THREAD

**Issue by CCChenhao997** [DoodleJZ/HPSG-Neural-Parser#15]
Can you provide the glove.gz ? Thx :)

**Comment by guhur** [comment]
1. Download glove 6B embedding zip file from https://nlp.stanford.edu/projects/glove/
2. Unzip it
3. Gzip the 100d file: gzip -k glove.6B.100d.txt 
4. Rename the produced file: mv glove.6B.100d.txt.gz glove.gz
